package:
    name: levmar 
    version: "2.6"

source:
    url: https://src.fedoraproject.org/repo/pkgs/rpms/levmar/levmar-2.6.tgz/sha512/5b4c64b63be9b29d6ad2df435af86cd2c2e3216313378561a670ac6a392a51bbf1951e96c6b1afb77c570f23dd8e194017808e46929fec2d8d9a7fe6cf37022b/levmar-2.6.tgz
    sha512: 5b4c64b63be9b29d6ad2df435af86cd2c2e3216313378561a670ac6a392a51bbf1951e96c6b1afb77c570f23dd8e194017808e46929fec2d8d9a7fe6cf37022b
    patches:
        - levmar-cmake-shared.patch

build:
    number: 3

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('c') }}
    host:
        - libopenblas 0.3.8
        - libcblas=3.8.0 *openblas
        - liblapack=3.8.0 *openblas
    run:
        - {{ pin_compatible('libopenblas', 'x.x.x') }}
        - {{ pin_compatible('libcblas') }}
        - {{ pin_compatible('liblapack') }}
    run_exports:
        - {{ pin_compatible('levmar', max_pin='x.x', min_pin='x.x') }}

test:
    commands:
        - lmdemo

about:
    home: http://users.ics.forth.gr/~lourakis/levmar/ 
    license: GPL2
    license_file: LICENSE
    summary: Levenberg-Marquardt nonlinear least squares algorithm

